### ISSUE TITLE
New text editor broke Drag N' Drop

### ISSUE THREAD

**Issue by ghost** [jbarczak/Pyramid#2]
The new HLSL/GLSL text control seems to not support Drag N' Drop for source files.

**Comment by jbarczak** [comment]
New text editor is eating the drag events for some reason.  I'll fix it as soon as I have a chance, but in the meantime,  it can be worked around by drag-dropping onto the scrollbar in the text editor.

**Comment by jbarczak** [comment]
Should be fixed now.
