### ISSUE TITLE
Remove compiled binary from "bin" and make a release out of it?

### ISSUE THREAD

**Issue by Gargaj** [jbarczak/Pyramid#4]
See https://github.com/jbarczak/Pyramid/releases ?

**Comment by jbarczak** [comment]
I've gone back and forth on this, but keeping an up to the minute binary checked in seems to be most convenient. If my pace of development somehow accelerates I'll reconsider point releases, but this project is really informal, and its simplest for me to test locally, push, and be able to pull the new bits down on other machines as necessary.
