### ISSUE TITLE
got crashed for pow function

### ISSUE THREAD

**Issue by shadercoder** [jbarczak/Pyramid#9]
i have  test a program
float getpow(float x, float y)
{
    return pow(x,y);
}

float4 main(float3 tex:TEXCOORD0) : SV_TARGET { return getpow(tex.x, tex.y).xxxx; }

but the Pyramid got crashed
change to  float4 main(float3 xx:TEXCOORD0) : SV_TARGET { return getpow(1, 6).xxxx; } is OK.

**Comment by jbarczak** [comment]
Seems to be a problem with CodeXL.  CodeXL seems to get hung for the first but not the second.   You can work around it by disabling the CodeXL backend in Tools->Options.   Narrowing the set of asics that CodeXL compiles against may also help.

**Comment by shadercoder** [comment]
ok,  it works 

this tool is really helpful when i read http://www.humus.name/Articles/Persson_LowLevelThinking.pdf
learning low level shading language optimizations
thanks
